---
title: "emotional-analysis"
output: html_notebook
---
setwd("C:/Users/zhaiy/Desktop/Python-r-emotion") 
script <- read.csv("data.csv", stringsAsFactors=FALSE)
install.packages("dplyr")  
install.packages("tidytext")  
install.packages("tidyr")  
install.packages("ggplot2") 
library(dplyr)  
library(tidytext)  
library(tidyr)  
library(ggplot2)  

tidy_script <- script %>%  
  unnest_tokens(word, text)  
head(tidy_script)  

tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  arrange(line) %>%  
  head(10)

tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  count(line, sentiment) %>%  
  arrange(line) %>%  
  head(10)  
  
tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  count(line, sentiment) %>%  
  mutate(index = as.numeric(line) %/% 5) %>%  
  arrange(index) %>%  
  head(10)
  
tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "positive") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10)  
  
tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "negative") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10)  

tidy_script %>%  
  anti_join(stop_words) %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "positive") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10)  
  
  
tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  count(line, sentiment) %>%  
  mutate(index = as.numeric(line) %/% 5) %>%  
  ggplot(aes(x=index, y=n, fill=sentiment)) %>%  
  + geom_col() 

tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  count(line, sentiment) %>%  
  mutate(index = as.numeric(line) %/% 5) %>%  
  ggplot(aes(x=index, y=n, fill=sentiment)) %>%  
  + geom_col() %>%  
  + facet_wrap(~sentiment, ncol=3)  

tidy_script %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "positive") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10)  
  
custom_stop_words <- bind_rows(stop_words,
  data_frame(word = c("don", "stark", "mother", "father", "daughter", "brother", "rock", "ground", "lord", "guard", "shoulder", "king", "main", "grace", "gate", "horse", "eagle", "servent"),  
  lexicon = c("custom")))  


tidy_script %>%  
  anti_join(custom_stop_words) %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "positive") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10) 

tidy_script %>%  
  anti_join(custom_stop_words) %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment == "negative") %>%  
  count(word) %>%  
  arrange(desc(n)) %>%  
  head(10) 


tidy_script %>%  
  anti_join(custom_stop_words) %>%  
  inner_join(get_sentiments("nrc")) %>%  
  filter(sentiment != "negative" & sentiment != "positive") %>%  
  count(line, sentiment) %>%  
  mutate(index = as.numeric(line) %/% 5) %>%  
  ggplot(aes(x=index, y=n, fill=sentiment)) %>%  
  + geom_col() %>%  
  + facet_wrap(~sentiment, ncol=3) 

